### ISSUE TITLE
Unable to locate executable file: psql

### ISSUE THREAD

**Issue by bschenz-kr** [Azure/postgresql#9]
running without azure credentials, but firewall rules that open to my runner. I'm getting this error:

Error: Error occurred while running action:
Error: Unable to locate executable file: psql. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

do you require that file to already be available on the runner? I had hoped that you do not since I chose this way to get around that requirement.

**Comment by arjgupta** [comment]
@bschenz-kr closing this issue. please share the data we requested earlier. If you are using private runner, then psql should already be installed on it.
